# Generated by Django 3.1.6 on 2021-03-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPigeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pigeon', models.CharField(max_length=30)),
                ('Des_pigeon', models.CharField(max_length=30)),
                ('img_pigeon', models.ImageField(max_length=30, upload_to='')),
            ],
        ),
    ]
