# Generated by Django 3.1.6 on 2021-03-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpigeon',
            name='img_pigeon',
        ),
    ]
