# Generated by Django 3.1.6 on 2021-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0002_remove_newpigeon_img_pigeon'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpigeon',
            name='img_pigeon',
            field=models.ImageField(default=1, max_length=30, upload_to=''),
            preserve_default=False,
        ),
    ]
