# Generated by Django 3.1.6 on 2021-03-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0003_newpigeon_img_pigeon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpigeon',
            old_name='Des_pigeon',
            new_name='des_pigeon',
        ),
    ]
