# Generated by Django 3.1.6 on 2021-03-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0005_auto_20210313_1601'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPigeons',
            new_name='NewPigeon',
        ),
    ]
