# Generated by Django 3.1.6 on 2021-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0006_auto_20210313_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpigeon',
            name='des_pigeon',
            field=models.CharField(max_length=300),
        ),
    ]
