# Generated by Django 3.1.6 on 2021-03-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0011_auto_20210328_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpigeon',
            name='img_pigeon',
            field=models.ImageField(upload_to='static/fichier'),
        ),
    ]
