# Generated by Django 3.1.6 on 2021-03-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0012_auto_20210328_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpigeon',
            name='img_pigeon',
            field=models.FileField(upload_to='static/fichier'),
        ),
    ]
