# Generated by Django 3.1.6 on 2021-03-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0013_auto_20210328_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpigeon',
            name='img_pigeon',
            field=models.FileField(upload_to='fichier'),
        ),
    ]
