from django.db import models

# Create your models here.

class NewDossier(models.Model):
    loca_sont_dans_les_lieux = models.CharField(max_length=50, default=000)
    loca_sont_pas_dans_les_lieux = models.CharField(max_length=50, default=000)
    oui_incident_dernier_mois = models.CharField(max_length=50, default=000)
    non_incident_dernier_mois = models.CharField(max_length=50, default=000)
    loca_dans_les_lieux_depuis = models.CharField(max_length=50, default=000)
    statut_locataire = models.CharField(max_length=50, default=000)
    models.DecimalField(max_digits=15, default=000, decimal_places=7)
    statut_garant_1 = models.CharField(max_length=50, default=000)
    models.DecimalField(max_digits=15, default=000, decimal_places=7)
    anciennete = models.CharField(max_length=50, default=000)
    date_fin_contrat = models.DateField(max_length=50, default=000)
    statut_locataire2 =  models.CharField(max_length=50, default=000)
    models.DecimalField(max_digits=15, default=000, decimal_places=7)
    statut_garant_2 = models.CharField(max_length=50, default=000)
    revenu_garant2 = models.DecimalField(max_digits=15, default=000, decimal_places=7)
    anciennete2 = models.CharField(max_length=50, default=000)
    date_fin_contrat2 = models.DateField(max_length=50, default=000)
    statut_locataire3 = models.CharField(max_length=50, default=000)
    revenus_du_locataire_3 = models.DecimalField(max_digits=15, default=000, decimal_places=7)
    statut_garant_3 = models.CharField(max_length=50, default=000)
    revenu_garant3 = models.DecimalField(max_digits=15, default=000, decimal_places=7)
    anciennete3 = models.CharField(max_length=50, default=000)
    date_fin_contrat3 = models.DateField(max_length=50, default=000)
    statut_locataire4 = models.CharField(max_length=50, default=000)
    revenus_du_locataire_4 = models.DecimalField(max_digits=15, default=000, decimal_places=7)
    statut_garant_4 = models.CharField(max_length=50, default=000)
    revenu_garant4 = models.DecimalField(max_digits=15, default=000, decimal_places=7)
    anciennete4 = models.CharField(max_length=50, default=000)
    date_fin_contrat4 = models.DateField(max_length=50, default=000)
    revenus_complement_foyer = models.DecimalField(max_digits=15, default=000, decimal_places=7)
    loyer_mensuel = models.DecimalField(max_digits=15, default=000, decimal_places=7)
    nom_1_loca = models.CharField(max_length=50, default=000)
    email_1_loca = models.EmailField(max_length=50, default=000)
    comment_loca_1 = models.CharField(max_length=50, default=000)
    file_justificatif = models.BooleanField(max_length=50, default=000)
    type_fichier = models.CharField(max_length=50, default=000)
    nom_1_loca2 = models.CharField(max_length=50, default=000)
    adresse_logement = models.CharField(max_length=50, default=000)
    date_signature_bail = models.DateField(max_length=50, default=000)

  
