# Generated by Django 3.1.6 on 2021-04-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewDossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loca_sont_dans_les_lieux', models.CharField(max_length=10, null=True)),
                ('loca_sont_pas_dans_les_lieux', models.CharField(max_length=10, null=True)),
                ('oui_incident_dernier_mois', models.CharField(max_length=10, null=True)),
                ('non_incident_dernier_mois', models.CharField(max_length=10, null=True)),
                ('loca_dans_les_lieux_depuis', models.CharField(max_length=10, null=True)),
                ('statut_locataire', models.CharField(max_length=50, null=True)),
                ('revenus_du_locataire_1', models.FloatField(default=1, max_length=30)),
                ('nom_1_loca', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('email_1_loca', models.EmailField(blank=True, default=0, max_length=50, null=True)),
                ('comment_loca_1', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('statut_garant_1', models.CharField(default=0, max_length=50, null=True)),
                ('revenu_garant1', models.FloatField(default=0, max_length=30)),
                ('anciennete', models.CharField(default=0, max_length=50, null=True)),
                ('date_fin_contrat', models.CharField(default=0, max_length=50, null=True)),
                ('statut_locataire2', models.CharField(default=0, max_length=50, null=True)),
                ('revenus_du_locataire_2', models.FloatField(default=1, max_length=30)),
                ('nom_1_loca_2', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('email_1_loca_2', models.EmailField(blank=True, default=0, max_length=50, null=True)),
                ('comment_loca_2', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('statut_garant_2', models.CharField(default=0, max_length=50, null=True)),
                ('revenu_garant2', models.FloatField(default=1, max_length=30)),
                ('anciennete2', models.CharField(default=0, max_length=50, null=True)),
                ('date_fin_contrat2', models.CharField(default=0, max_length=50)),
                ('statut_locataire3', models.CharField(default=0, max_length=50, null=True)),
                ('revenus_du_locataire_3', models.FloatField(default=1, max_length=30)),
                ('nom_1_loca_3', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('email_1_loca_3', models.EmailField(blank=True, default=0, max_length=50, null=True)),
                ('comment_loca_3', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('statut_garant_3', models.CharField(default=0, max_length=50, null=True)),
                ('revenu_garant3', models.FloatField(default=1, max_length=30)),
                ('anciennete3', models.CharField(default=0, max_length=50, null=True)),
                ('date_fin_contrat3', models.CharField(default=0, max_length=50, null=True)),
                ('statut_locataire4', models.CharField(default=0, max_length=50, null=True)),
                ('revenus_du_locataire_4', models.FloatField(default=1, max_length=30)),
                ('nom_1_loca_4', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('email_1_loca_4', models.EmailField(blank=True, default=0, max_length=50, null=True)),
                ('comment_loca_4', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('statut_garant_4', models.CharField(default=0, max_length=50, null=True)),
                ('revenu_garant4', models.FloatField(default=1, max_length=30)),
                ('anciennete4', models.CharField(default=0, max_length=50, null=True)),
                ('date_fin_contrat4', models.CharField(default=0, max_length=50, null=True)),
                ('revenus_complement_foyer', models.FloatField(blank=True, default=1, max_length=30)),
                ('loyer_mensuel', models.FloatField(blank=True, default=1, max_length=30)),
                ('votre_nom', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('adresse_logement', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('date_signature_bail', models.DateField(blank=True, default=0, max_length=50, null=True)),
            ],
        ),
    ]
