# Generated by Django 3.1.6 on 2021-04-07 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DossierVerifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdossier',
            name='file_justificatif',
        ),
        migrations.RemoveField(
            model_name='newdossier',
            name='nom_1_loca2',
        ),
        migrations.RemoveField(
            model_name='newdossier',
            name='type_fichier',
        ),
        migrations.AddField(
            model_name='newdossier',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='comment_loca_2',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='comment_loca_3',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='comment_loca_4',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='email_1_loca_2',
            field=models.EmailField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='email_1_loca_3',
            field=models.EmailField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='email_1_loca_4',
            field=models.EmailField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='nom_1_loca_2',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='nom_1_loca_3',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='nom_1_loca_4',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='revenu_garant1',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='revenus_du_locataire_1',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='revenus_du_locataire_2',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='votre_nom',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='adresse_logement',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='anciennete',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='anciennete2',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='anciennete3',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='anciennete4',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='comment_loca_1',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat2',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat3',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat4',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_signature_bail',
            field=models.DateField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='email_1_loca',
            field=models.EmailField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='loca_dans_les_lieux_depuis',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='loca_sont_dans_les_lieux',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='loca_sont_pas_dans_les_lieux',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='loyer_mensuel',
            field=models.FloatField(blank=True, default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='nom_1_loca',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='non_incident_dernier_mois',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='oui_incident_dernier_mois',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenu_garant2',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenu_garant3',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenu_garant4',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenus_complement_foyer',
            field=models.FloatField(blank=True, default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenus_du_locataire_3',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenus_du_locataire_4',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_garant_1',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_garant_2',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_garant_3',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_garant_4',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_locataire',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_locataire2',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_locataire3',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_locataire4',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
