# Generated by Django 3.1.6 on 2021-03-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdossier',
            name='date_fin_contrat4',
        ),
        migrations.RemoveField(
            model_name='newdossier',
            name='file_justificatif',
        ),
        migrations.RemoveField(
            model_name='newdossier',
            name='loyer_mensuel',
        ),
        migrations.RemoveField(
            model_name='newdossier',
            name='revenu_garant2',
        ),
        migrations.RemoveField(
            model_name='newdossier',
            name='revenu_garant3',
        ),
        migrations.RemoveField(
            model_name='newdossier',
            name='revenu_garant4',
        ),
        migrations.RemoveField(
            model_name='newdossier',
            name='revenus_complement_foyer',
        ),
        migrations.RemoveField(
            model_name='newdossier',
            name='revenus_du_locataire_3',
        ),
        migrations.RemoveField(
            model_name='newdossier',
            name='revenus_du_locataire_4',
        ),
        migrations.RemoveField(
            model_name='newdossier',
            name='type_fichier',
        ),
        migrations.AddField(
            model_name='newdossier',
            name='revenus_du_locataire_1',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat2',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat3',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
