# Generated by Django 3.1.6 on 2021-03-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0004_auto_20210325_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdossier',
            name='date_fin_contrat4',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
