# Generated by Django 3.1.6 on 2021-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0005_newdossier_date_fin_contrat4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdossier',
            name='loca_sont_dans_les_lieux',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
