# Generated by Django 3.1.6 on 2021-03-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0007_auto_20210325_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdossier',
            name='adresse_logement',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='anciennete',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='anciennete2',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='anciennete4',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='comment_loca_1',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat2',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat3',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat4',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_signature_bail',
            field=models.DateField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='email_1_loca',
            field=models.EmailField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='loca_dans_les_lieux_depuis',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='nom_1_loca',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='nom_1_loca2',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenus_du_locataire_1',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_garant_1',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_garant_2',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_garant_3',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_garant_4',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_locataire',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_locataire2',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_locataire3',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_locataire4',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
