# Generated by Django 3.1.6 on 2021-03-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0009_auto_20210325_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdossier',
            name='anciennete3',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenus_du_locataire_1',
            field=models.FloatField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
