# Generated by Django 3.1.6 on 2021-03-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0014_auto_20210325_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdossier',
            name='revenus_du_locataire_1',
            field=models.FloatField(blank=True, default=1, max_length=30),
        ),
    ]
