# Generated by Django 3.1.6 on 2021-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0015_auto_20210325_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdossier',
            name='loyer_mensuel',
            field=models.FloatField(blank=True, default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='revenu_garant1',
            field=models.FloatField(blank=True, default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='revenu_garant2',
            field=models.FloatField(blank=True, default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='revenu_garant3',
            field=models.FloatField(blank=True, default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='revenu_garant4',
            field=models.FloatField(blank=True, default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='revenus_complement_foyer',
            field=models.FloatField(blank=True, default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='revenus_du_locataire_2',
            field=models.FloatField(blank=True, default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='revenus_du_locataire_3',
            field=models.FloatField(blank=True, default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='revenus_du_locataire_4',
            field=models.FloatField(blank=True, default=1, max_length=30),
        ),
    ]
