# Generated by Django 3.1.6 on 2021-03-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0016_auto_20210325_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdossier',
            name='anciennete',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='anciennete2',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='anciennete3',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='anciennete4',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat2',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat3',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='date_fin_contrat4',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenu_garant1',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenu_garant2',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenu_garant3',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenu_garant4',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenus_du_locataire_2',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenus_du_locataire_3',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='revenus_du_locataire_4',
            field=models.FloatField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_garant_1',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_garant_2',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_garant_3',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_garant_4',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_locataire2',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_locataire3',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_locataire4',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
