# Generated by Django 3.1.6 on 2021-03-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0021_auto_20210325_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdossier',
            name='revenus_du_locataire_1',
            field=models.FloatField(null=True),
        ),
    ]
