# Generated by Django 3.1.6 on 2021-03-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0022_auto_20210326_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdossier',
            name='revenus_du_locataire_1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
