# Generated by Django 3.1.6 on 2021-03-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0027_auto_20210326_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdossier',
            name='revenus_du_locataire_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='statut_locataire',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
