# Generated by Django 3.1.6 on 2021-03-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0028_auto_20210326_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdossier',
            name='revenu_garant1',
            field=models.FloatField(default=0, max_length=30),
        ),
    ]
