# Generated by Django 3.1.6 on 2021-03-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0030_auto_20210326_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdossier',
            name='loca_dans_les_lieux_depuis',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='loca_sont_dans_les_lieux',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='loca_sont_pas_dans_les_lieux',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='non_incident_dernier_mois',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='oui_incident_dernier_mois',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
