# Generated by Django 3.1.6 on 2021-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0031_auto_20210326_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newdossier',
            old_name='nom_1_loca2',
            new_name='votre_nom',
        ),
        migrations.AddField(
            model_name='newdossier',
            name='comment_loca_2',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='comment_loca_3',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='comment_loca_4',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='email_1_loca_2',
            field=models.EmailField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='email_1_loca_3',
            field=models.EmailField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='email_1_loca_4',
            field=models.EmailField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='nom_1_loca_2',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='nom_1_loca_3',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newdossier',
            name='nom_1_loca_4',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
