# Generated by Django 3.1.6 on 2021-03-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0033_auto_20210326_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdossier',
            name='loca_dans_les_lieux_depuis',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='loca_sont_dans_les_lieux',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='loca_sont_pas_dans_les_lieux',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='non_incident_dernier_mois',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newdossier',
            name='oui_incident_dernier_mois',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
