# Generated by Django 3.1.6 on 2021-03-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0035_newdossier_user'),
        ('compte', '0002_auto_20210326_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='des',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='NewDossier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DossierVerifier.newdossier'),
        ),
    ]
