# Generated by Django 3.1.6 on 2021-03-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DossierVerifier', '0035_newdossier_user'),
        ('compte', '0003_auto_20210326_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='NewDossier',
        ),
        migrations.AddField(
            model_name='profile',
            name='NewDossier',
            field=models.ManyToManyField(to='DossierVerifier.NewDossier'),
        ),
    ]
